[project]
name = "twitter-bot-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "viseryon", email = "viseryon@users.noreply.github.com" }]
requires-python = ">=3.11"
dependencies = ["tweepy>=4.14.0"]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
