[project]
name = "mylogging"
version = "1.0.0"
description = "My loggin setup"
readme = "README.md"
authors = [
    { name = "viseryon", email = "viseryon@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
