[project]
name = "gpw-heatmaps"
version = "1.0.1"
description = "Project to post heatmaps with gpw stocks"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plotly[kaleido]>=6.3.1",
    "pytz>=2024.2",
    "requests>=2.32.3",
    "yahooquery>=2.4.1",
    "kaleido>=0.2.1",
]
